import sys
import os
import json

# Add the parent directory to the path so we can import app modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database import SessionLocal, engine, Base
from app.models import JobRole

# Create tables if they don't exist
Base.metadata.create_all(bind=engine)

def seed_jobs():
    db = SessionLocal()
    
    # Check if we already have jobs
    if db.query(JobRole).count() > 0:
        print("Jobs already seeded.")
        return

    jobs = [
        {
            "title": "Software Engineer",
            "description": "Develop, test, and maintain software applications. Experience with Python, JavaScript, and SQL required.",
            "required_skills": json.dumps(["Python", "JavaScript", "SQL", "Git", "REST APIs", "Docker"])
        },
        {
            "title": "Data Scientist",
            "description": "Analyze large datasets to extract insights. Proficiency in Python, R, and machine learning libraries is essential.",
            "required_skills": json.dumps(["Python", "Machine Learning", "Pandas", "NumPy", "SQL", "Data Visualization"])
        },
        {
            "title": "Frontend Developer",
            "description": "Build responsive and interactive user interfaces using React, Vue, or Angular.",
            "required_skills": json.dumps(["JavaScript", "React", "HTML", "CSS", "TypeScript", "Redux"])
        },
        {
            "title": "Backend Developer",
            "description": "Design and implement server-side logic and database schemas. Knowledge of Node.js, Python, or Go is preferred.",
            "required_skills": json.dumps(["Node.js", "Python", "Go", "Database Design", "API Development", "Microservices"])
        },
        {
            "title": "DevOps Engineer",
            "description": "Manage infrastructure and deployment pipelines. Experience with AWS, Docker, and Kubernetes is a plus.",
            "required_skills": json.dumps(["AWS", "Docker", "Kubernetes", "CI/CD", "Linux", "Terraform"])
        },
        {
            "title": "Product Manager",
            "description": "Define product vision and roadmap. Strong communication and leadership skills required.",
            "required_skills": json.dumps(["Product Management", "Agile", "User Research", "Roadmapping", "Communication", "Data Analysis"])
        },
        {
            "title": "UX/UI Designer",
            "description": "Design user interfaces and user experiences. Proficiency in Figma and Adobe Creative Suite is key.",
            "required_skills": json.dumps(["Figma", "UI Design", "UX Research", "Prototyping", "Wireframing", "Adobe XD"])
        },
         {
            "title": "Machine Learning Engineer",
            "description": "Build and deploy machine learning models. scalable ML systems.",
            "required_skills": json.dumps(["Python", "TensorFlow", "PyTorch", "MLops", "Cloud Computing", "Deep Learning"])
        }
    ]

    for job_data in jobs:
        job = JobRole(
            title=job_data["title"],
            description=job_data["description"],
            required_skills=job_data["required_skills"],
            embedding_vector=json.dumps([]) # Placeholder for now, would be generated by ML service
        )
        db.add(job)
    
    db.commit()
    print(f"Seeded {len(jobs)} job roles.")
    db.close()

if __name__ == "__main__":
    seed_jobs()
